name: CI/CD Deploy

on:
  push:
    branches: [develop] #dev에 push 될 때 마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #GitHub에서 제공하는 ubuntu-latest에서 실행

    steps:
      - name: Checkout repository #깃허브 저장소의 코드를 runner로 가져옴
        uses: actions/checkout@v4

      - name: Set up Docker Buildx #도커 setup
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote-server:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vote-server:latest
            sudo docker-compose down
            sudo docker-compose up -d
